name: Terraform CI/CD

on:
  issue_comment:
    types: [created]
  pull_request:
    branches:
      - master

jobs:
    security_check:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'test this please')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Checkov
      run: python -m pip install --upgrade pip checkov

    - name: Run Checkov Security Scan
      run: checkov -d .

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

